version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=sqlite:///./football_predictor.db
      - SECRET_KEY=your-secret-key-change-in-production
      - DEBUG=true
      - HOST=0.0.0.0
      - PORT=8001
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    restart: unless-stopped
    networks:
      - football-predictor

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8001
      - NEXT_PUBLIC_APP_NAME=Football Predictor
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - football-predictor

  # Telegram Bot
  telegram-bot:
    build:
      context: ./telegram-bot
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - TELEGRAM_BOT_TOKEN=your-telegram-bot-token
      - API_BASE_URL=http://backend:8001
      - DATABASE_URL=sqlite:///./football_predictor.db
      - TELEGRAM_WEBHOOK_PORT=8002
    volumes:
      - ./telegram-bot:/app
      - bot_data:/app/data
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - football-predictor

  # Redis (for Celery background tasks)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - football-predictor

  # Nginx (reverse proxy)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    networks:
      - football-predictor

volumes:
  backend_data:
  bot_data:
  redis_data:

networks:
  football-predictor:
    driver: bridge